ASSET_SOURCES = [
    {
        "id": "local_ffmpeg_effects",
        "name": "自建 FFmpeg 特效库",
        "types": ["visual_effect", "transition", "overlay"],
        "license": "internal",
        "commercial_allowed": True,
        "attribution_required": False,
        "integration_priority": 1,
        "notes": "默认基础效果，无版权风险，适合烟花、闪白、速度线、胶片颗粒、标题条。",
    },
    {
        "id": "lotsofsounds",
        "name": "lotsofsounds",
        "types": ["sound_effect"],
        "license": "CC0",
        "commercial_allowed": True,
        "attribution_required": False,
        "integration_priority": 1,
        "url": "https://www.lotsofsounds.com/sounds",
    },
    {
        "id": "freesound",
        "name": "Freesound",
        "types": ["sound_effect", "ambience", "transition_sound"],
        "license": "CC0/CC BY/CC BY-NC",
        "commercial_allowed": "depends_on_asset",
        "attribution_required": "depends_on_asset",
        "integration_priority": 2,
        "url": "https://freesound.org/docs/api",
        "notes": "自动使用前需要过滤 CC BY-NC，并保存作者和来源。",
    },
    {
        "id": "lottiefiles",
        "name": "LottieFiles Free Animations",
        "types": ["sticker", "overlay", "motion_graphics"],
        "license": "Lottie Simple License",
        "commercial_allowed": True,
        "attribution_required": False,
        "integration_priority": 2,
        "url": "https://help.lottiefiles.com/animation-licensing-basics-",
        "notes": "不做批量镜像，不把原始动画文件作为独立素材转售。",
    },
    {
        "id": "pexels",
        "name": "Pexels",
        "types": ["b_roll", "photo", "video"],
        "license": "Pexels License",
        "commercial_allowed": True,
        "attribution_required": False,
        "integration_priority": 3,
        "url": "https://www.pexels.com/api/documentation/",
        "notes": "适合补 B-roll；不要单独分发素材或暗示人物品牌背书。",
    },
    {
        "id": "openverse",
        "name": "Openverse",
        "types": ["image", "audio"],
        "license": "Creative Commons/Public Domain",
        "commercial_allowed": "depends_on_asset",
        "attribution_required": "depends_on_asset",
        "integration_priority": 3,
        "url": "https://docs.openverse.org/api/",
        "notes": "入库前需要验证单个作品许可证。",
    },
    {
        "id": "mixkit",
        "name": "Mixkit",
        "types": ["music", "sound_effect", "video", "template"],
        "license": "Mixkit Free License",
        "commercial_allowed": True,
        "attribution_required": False,
        "integration_priority": 3,
        "url": "https://mixkit.co/license/",
        "notes": "免费授权但非开源；不要作为独立素材二次分发。",
    },
]


def recommended_sources() -> list[dict]:
    return sorted(ASSET_SOURCES, key=lambda item: item["integration_priority"])
